version: "3"

services:
  app-flask:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-flask
    container_name: app-flask
    ports:
      - "8000:80"
    depends_on:
    - redis
  redis:
    image: redis